version: 0.2

phases:
  install:
    runtime-versions:
      powershell: "7.2.4"
  pre_build:
    commands:
      # - aws ec2 run-instances --image-id ami-04adeb9ef364bcb6a --count 1 --instance-type t2.micro --key-name ecs-keys --security-group-ids sg-01592497c48aacf6d --subnet-id subnet-0b50655229b02d022 --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=MontyCloud}]' --user-data file://docker_install_script.sh > instance.json
      - Invoke-WebRequest "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/windows/SessionManagerPluginSetup.exe" -OutFile "SessionManagerPluginSetup.exe"
      - powershell.exe -Command "& 'C:\Program Files\Amazon\SessionManagerPluginSetup.exe' /install /quiet"
      # - $env:PATH += ";C:\Program Files\Amazon\SSM\Plugins\session-manager-plugin\bin"
      # - $instanceId = (Get-Content instance.json | ConvertFrom-Json).Instances.InstanceId
  build:
    commands:
      # - sleep 300
      - aws ssm start-session --target i-083889343e2e7f585 
      - docker login -u AWS -p $(aws ecr get-login-password --region us-west-2) 276954963877.dkr.ecr.us-west-2.amazonaws.com
      - docker pull 276954963877.dkr.ecr.us-west-2.amazonaws.com/montycloud:1.0
      - docker run -p 8001:8001 276954963877.dkr.ecr.us-west-2.amazonaws.com/montycloud:1.0
      - exit
  post_build:
    commands:
      # - aws ec2 stop-instances --instance-ids $instanceId
