version: 0.2

phases:
  install:
    runtime-versions:
      powershell: "7.2.4"
  pre_build:
    commands:
      - aws ec2 run-instances --image-id ami-04adeb9ef364bcb6a --count 1 --instance-type t2.micro --key-name ecs-keys --security-group-ids sg-01592497c48aacf6d --subnet-id subnet-0b50655229b02d022 --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=MontyCloud}]' --user-data file://docker_install_script.sh > instance.json
      - $instanceId = (Get-Content instance.json | ConvertFrom-Json).Instances.InstanceId
  build:
    commands:
      # Get the public IP address of the EC2 instance
      # - >
      #   ipAddress=$(aws ec2 describe-instances --instance-ids $instanceId --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
      # SSH into the EC2 instance and execute the commands
      # - ssh -o StrictHostKeyChecking=no ec2-user@$ipAddress -i /ecs-keys.pem 'aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 276954963877.dkr.ecr.us-west-2.amazonaws.com'
      # - ssh -o StrictHostKeyChecking=no ec2-user@$ipAddress -i /ecs-keys.pem 'docker pull 276954963877.dkr.ecr.us-west-2.amazonaws.com/montycloud:1.0'
      # - ssh -o StrictHostKeyChecking=no ec2-user@$ipAddress -i /ecs-keys.pem 'docker run -p 8001:8001 276954963877.dkr.ecr.us-west-2.amazonaws.com/montycloud:1.0'
      # - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 276954963877.dkr.ecr.us-west-2.amazonaws.com
      # - docker pull 276954963877.dkr.ecr.us-west-2.amazonaws.com/montycloud:1.0
      # - docker run -p 8001:8001 276954963877.dkr.ecr.us-west-2.amazonaws.com/montycloud:1.0
  post_build:
    commands:
      - aws ec2 stop-instances --instance-ids $instanceId
